# Sidebar navigation

- label: 'معرفی'
  link: '/'

- label: دوره مقدماتی
  items:
    - label: '۱-مقدمه'
      link: '/usage/creating-docs'
    - label: '۲-مقدمه‌ای بر Python'
      link: '/usage/navigation'
    - label: '۳-مقدمه ای بر NumPy'
      link: '/usage/shadowing'
- label: بیشتر
  items:
    - label: پرسش و پاسخ
      link: /faq
    - label: گواهی اتمام دوره
      link: /changelog
- label: ارجاع
  items:
    - label: 'تالار گفتگو' 
      link: https://github.com/SadraFinance/SadraAcademy
    - label: ' گیت هاب ' 
      link: https://github.com/SadraFinance/SadraAcademy
